In [1]:
import numpy as np

Tạo một vector có độ dài là 5

In [3]:
#vector ngang
hoz_vec = np.array([10,20,30,40,50])
len(hoz_vec)

5

In [5]:
# vector dọc
ver_vec = np.array([[2],
                    [4],
                    [6],
                    [10],
                    [12]
                    ])
len(ver_vec)

5

Tạo 1 ma trận có kích thước 3x3 (numpy)

In [6]:
#Tạo một ma trận 0 3x3 
matrx = np.zeros((3, 3))
matrx

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Tạo 2 ma trận A,B kích thước 2x3

In [7]:
rows = 2
cols = 3

In [9]:
A = np.random.rand(rows, cols)
A

array([[0.10944321, 0.30677361, 0.36833917],
       [0.87848047, 0.92356979, 0.12329458]])

In [10]:
B = np.random.rand(rows, cols)
B

array([[0.26249921, 0.86851503, 0.78813158],
       [0.40625467, 0.24623555, 0.7770374 ]])