In [1]:
import numpy as np

Tạo một vector có độ dài là 5

In [3]:
#vector ngang
hoz_vec = np.array([10,20,30,40,50])
len(hoz_vec)

5

In [5]:
# vector dọc
ver_vec = np.array([[2],
                    [4],
                    [6],
                    [10],
                    [12]
                    ])
len(ver_vec)

5

Tạo 1 ma trận có kích thước 3x3 (numpy)

In [12]:
#Tạo một ma trận radom 3x3 
matrx = np.random.rand(3, 3)
matrx

array([[0.30279229, 0.26425558, 0.73271598],
       [0.5536205 , 0.39153414, 0.19086425],
       [0.80155545, 0.07493536, 0.10305178]])

Tạo 2 ma trận A,B kích thước 2x3, tính tích 2 ma trận

In [7]:
rows = 2
cols = 3

In [9]:
A = np.random.rand(rows, cols)
A

array([[0.10944321, 0.30677361, 0.36833917],
       [0.87848047, 0.92356979, 0.12329458]])

In [10]:
B = np.random.rand(rows, cols)
B

array([[0.26249921, 0.86851503, 0.78813158],
       [0.40625467, 0.24623555, 0.7770374 ]])

In [13]:
np.dot(A, matrx)

array([[0.49821899, 0.17663495, 0.17670091],
       [0.87613172, 0.60299159, 0.83265886]])

In [14]:
np.dot(B, matrx)

array([[1.19204162, 0.46847909, 0.4393242 ],
       [0.88217039, 0.26199227, 0.42474194]])

Xuất các phần tử thuộc dòng 1 cột 2 của A

In [17]:
#Dòng và cột của ma trận bắt đầu từ 0
A[1, 2]

0.12329458240540814

Xuất 2 dòng, 2 cột đầu tiên của A

In [48]:
A[0:2, 0:2]

array([[0.10944321, 0.30677361],
       [0.87848047, 0.92356979]])

Xuất 2 dòng, 2 cột cuối của A

In [49]:
A[0:2, 1:3]

array([[0.30677361, 0.36833917],
       [0.92356979, 0.12329458]])